server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: universidad-service
          uri: lb://universidad-service
          predicates:
            - Path=/universidad/**
        - id: docentes-service
          uri: lb://docentes-service
          predicates:
            - Path=/docentes/**
        - id: aulas-service
          uri: lb://aulas-service
          predicates:
            - Path=/aulas/**