server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: instance-multiples
          uri: https://github.com/Resarbo/microU
          search-paths: config-data
  application:
    name: config-service
